#!/usr/bin/env ruby

require 'json'

host = ENV.fetch('STAGE_URL', 'https://stagesite.com/branch/{{BRANCH}}/')

pulls = JSON.parse(STDIN.read)
pulls.each do |req|
  link = host.gsub('{{BRANCH}}', req['branch'])
  unless req['body'].include?(link)
    req['modified'] = true
    req['body'] = "[Staged Installation](#{link})\n\n#{req['body']}"
  end
end

puts pulls.to_json

